### ISSUE TITLE
Getting "Connection Refused"

### ISSUE THREAD

**Issue by gbeyer3** [vpenso/prometheus-slurm-exporter#86]
Hello, I built slurm-exporter, and running is foreground in terminal per DEVELOPMENT.md.    Added node to my prometheus.yml and cycled prom.   RHEL 7.9 node.
 
 ./prometheus-slurm-exporter --listen-address="0.0.0.0:9500" -gpus-acct
INFO[0000] Starting Server: 0.0.0.0:9500                 source="main.go:59"
INFO[0000] GPUs Accounting: true                         source="main.go:60"

However, in 2nd terminal window of my node,

curl http://localhost:9500/metrics
curl: (7) Failed connect to localhost:9500; Connection refused

And if I ps: it shows:

ps -ef | grep prometheus-slurm-exporter
gbeyer3  238618 225323  0 15:26 pts/1    00:00:00 grep --color=auto prometheus-slurm-exporter

So it _seems_ to not be running.  Thought it shows running in foreground in 1st terminal

Can someone suggest a solution?

Thanks

**Comment by gbeyer3** [comment]
Correction - I was curling from the wrong node (facepalm)

So did it again from the slurm node:

curl http://localhost:9500/metrics
curl: (52) Empty reply from server

In the terminal where I have the slurm-exporter running in foreground, the exporter crashed:

 ./prometheus-slurm-exporter --listen-address="0.0.0.0:9500" -gpus-acct
INFO[0000] Starting Server: 0.0.0.0:9500                 source="main.go:59"
INFO[0000] GPUs Accounting: true                         source="main.go:60"

------when I excute the curl in the other terminal, this happens-------------

panic: runtime error: index out of range [4] with length 4

goroutine 40 [running]:
main.ParseNodeMetrics(0xc00017e000, 0x25e, 0x600, 0x87080d)
	/storage/home/hhiveman1/gbeyer3/prometheus-slurm-exporter/node.go:56 +0x6d6
main.NodeGetMetrics(0x1)
	/storage/home/hhiveman1/gbeyer3/prometheus-slurm-exporter/node.go:40 +0x2a
main.(*NodeCollector).Collect(0xc000097740, 0xc0000a0ea0)
	/storage/home/hhiveman1/gbeyer3/prometheus-slurm-exporter/node.go:128 +0x37
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/storage/home/hhiveman1/gbeyer3/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x12b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/storage/home/hhiveman1/gbeyer3/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:535 +0xe4d
